version: '3.5'

services:

    api-listra:
        build: ./app
        container_name: api-listra
        ports: 
            - "8080:8080"
        volumes: 
            - ../.:/var/www
        tty: true
        entrypoint: dockerize -wait tcp://db-listra:3306 -timeout 40s .docker/app/entrypoint.sh
        depends_on:
            - db-listra
    
    nginx-listra:
        build: ./nginx
        container_name: nginx-listra
        restart: always
        tty: true
        ports:
            - "80:80"
            - "8000:8000"
        volumes:
            - ../.:/var/www
        depends_on:
            - api-listra
    
    db-listra:
        build: ./mysql
        command: --innodb-use-native-aio=0
        container_name: db-listra
        restart: always
        tty: true
        ports:
            - "3306:3306"
        volumes:
            - ./mysql/data:/var/lib/mysql
            - ./mysql/entrypoint:/docker-entrypoint-initdb.d
        environment:
            - MYSQL_ROOT_PASSWORD=root